/* Single source of truth for all Leva defaults.
   Export → Copy JSON, paste over `defaults` below, refresh. */

export const defaults = {
  scene: {
    bg: '#18202e',
    envPreset: 'dawn',
    envIntensity: 0.3,
    fov: 21,
    showShadows: false,
    shadowOpacity: 0.5,
    shadowBlur: 2.4,
  },
  gradient: {
    enabled: false,
    color1: '#0b0d1c',
    color2: '#1a0d2b',
    angle: 203,
  },
  orbit: {
    enabled: true,
    azimuthRangeDeg: 38,
    polarRangeUpDeg: 28,
    polarRangeDownDeg: 28,
    damping: 0.08,
    autoRotate: false,
    autoRotateSpeed: 0.4,
  },
  hero: {
    scale: 0.585,
    tiltX: 4.5,
    tiltY: 7,
    tiltStrength: 2,
    tiltDamping: 0.04,
    idleAmpY: 0.03,
    idleAmpX: 0.02,
    idleFreq: 0.99,
    posX: 0, posY: 0.11, posZ: 0,
    rotX: 0, rotY: 0, rotZ: 0,
  },
  physics: {
    enabled: true,
    gravity: -2.3,
    debug: false,
  },
  eggs: {
    enabled: false,
    count: 16,
    useCustomGLB: false,
    customGLBPath: '/models/egg.glb',
    customColliderRadius: 0.5,
    spreadX: 4.5, spreadZ: 3.5,
    spawnTop: 5.5, spawnBottom: -5,
    scaleMin: 0.4, scaleMax: 0.9,
    fallSpeedMin: 0.05, fallSpeedMax: 0.25,
    spinMin: 0.1, spinMax: 0.5,
    restitution: 0.35, friction: 0.7,
    mass: 0.18, linearDamping: 0.65, angularDamping: 0.55,
    lengthA: 0.6, widthB: 0.44, eggness: 0.37,
    yolkRadius: 0.2, yolkBulge: 0.55, yolkOffsetY: -0.05,
    whiteColor: '#f7efe1',
    capColor: '#e9dec7',
    yolkColor: '#ffb02e',
    yolkEmissive: '#ff7a00',
    yolkEmissiveIntensity: 0.25,
    yolkRoughness: 0.32,
    roughness: 0.6, metalness: 0.04,
  },
  naruto: {
    enabled: true,
    count: 28,
    spreadX: 3.2, spreadZ: 0.8,
    spawnTop: 4.7, spawnBottom: -5.7,
    scaleMin: 0.26, scaleMax: 0.47,
    fallSpeedMin: 0.05, fallSpeedMax: 0.28,
    spinMin: 0.2, spinMax: 0.9,
    restitution: 0.49, friction: 0.63,
    mass: 0.77, linearDamping: 0.55, angularDamping: 0.45,
    points: 18,
    baseRadius: 0.365, petalDepth: 0.025, petalSharpness: 0.85,
    thickness: 0.045, bevelSize: 0.024, bevelThickness: 0.056, bevelSegments: 2,
    spiralRadiusFrac: 0.57, turns: 1.4, lineWidth: 16,
    pink: '#ff80a4',
    white: '#fbfbf6',
    sideColor: '#fbfbf6',
    roughness: 0.5, metalness: 0.05,
  },
  lights: {
    ambient: 0.55,
    keyIntensity: 5,
    keyColor: '#ffffff',
    keyX: -10, keyY: 8.6, keyZ: -10,
    rimIntensity: 0.4,
    rimColor: '#177cff',
  },
  fx: {
    enabled: true,
    bloomOn: true, bloomIntensity: 1.32, bloomThreshold: 0.93, bloomSmoothing: 0.26,
    dofOn: false, dofFocus: 0.016, dofLength: 0.062, dofBokeh: 0,
    chromaOn: false, chromaOffset: 0,
    gradeOn: false, brightness: -0.09, contrast: -0.11, saturation: 0.05, hueShift: 0,
    vignetteOn: true, vignetteOffset: 0.42, vignetteDark: 0.71,
    noiseOn: false, noiseOpacity: 0,
  },
  pressFx: {
    pixelateOn: false,
    dotscreenOn: true,
    glitchOn: false,
    scanlineOn: false,
    sepiaOn: false,
    desaturateOn: false,
    bloomburstOn: false,
    chromaburstOn: false,
    colorAverageOn: false,
    noiseBurstOn: false,
    maxStrength: 0.03,
    durationIn: 0.4,
    durationOut: 1.7,
    shakeOn: true,
    shakePosIntensity: 0.05,
    shakeRotIntensity: 0.06,
    shakeFreq: 7.4,
    shakeSwing: 2.1,
  },
  buttonStyle: {
    label: 'Prenota un tavolo',
    bg: '#ffffff',
    text: '#000000',
    border: '#ffffff',
    hoverBg: '#ff638c',
    hoverText: '#000000',
    fontSize: 20,
    paddingX: 64,
    paddingY: 24,
    radius: 999,
    staggerEach: 0.02,
  },
}
